//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.02 at 12:33:40 PM IST 
//


package com.jspiders.myjavaproj.companystandard.college.fromsxd;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _College_QNAME = new QName("", "college");
    private final static QName _StudentInfo_QNAME = new QName("", "student-info");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link College }
     * 
     */
    public College createCollege() {
        return new College();
    }

    /**
     * Create an instance of {@link Student }
     * 
     */
    public Student createStudent() {
        return new Student();
    }

    /**
     * Create an instance of {@link College.StudentList }
     * 
     */
    public College.StudentList createCollegeStudentList() {
        return new College.StudentList();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link College }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "college")
    public JAXBElement<College> createCollege(College value) {
        return new JAXBElement<College>(_College_QNAME, College.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Student }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "student-info")
    public JAXBElement<Student> createStudentInfo(Student value) {
        return new JAXBElement<Student>(_StudentInfo_QNAME, Student.class, null, value);
    }

}
